#!/usr/bin/env bash
# localhost-u 127.0.0.2-yə, facebook.com-u isə 8.8.8.8-ə yönləndirir

# \s* istənilən sayda boşluq və ya tab deməkdir. Bu, dəqiq tapmağı təmin edir.
sed 's/127.0.0.1\s*localhost/127.0.0.2 localhost/g' /etc/hosts > /tmp/hosts_temp

# facebook.com yoxdursa əlavə edirik, varsa IP-sini dəyişirik
if grep -q "facebook.com" /tmp/hosts_temp; then
    sed -i 's/.*facebook.com/8.8.8.8 facebook.com/g' /tmp/hosts_temp
else
    echo "8.8.8.8 facebook.com" >> /tmp/hosts_temp
fi

cat /tmp/hosts_temp > /etc/hosts
rm /tmp/hosts_temp
