#!/usr/bin/env bash
# Localhost domenini 127.0.0.2 ünvanına yönləndirir

# /etc/hosts faylındakı köhnə localhost tərifini yeni IP ilə əvəz edir və ya əlavə edir
sudo sed -i 's/127.0.0.1\s*localhost/127.0.0.2 localhost/g' /etc/hosts
